/**
 plant("@", 3, 3, 25) ➞ "---@@@---@@@---@@@"
// Water gives the length of the stem portions between flowers.
// Water gives the total number of segments.
// Fertilizer gives the length of flowers clusters.
// In this case the temperature is in the acceptable range 20°C | 30°C
plant("#", 1, 5, 30) ➞ "-#####"
plant("&", 5, 1, 20) ➞ "-----&-----&-----&-----&-----&"
plant("§", 3, 3, 15) ➞ "---------§"

● seed (string) determines the type of ﬂowers generated by the plant.
● water (integer) each unit of water extends the portion of stem between the
ﬂowers, and gives the total number of segments (stem + ﬂowers) of the plant.
● fert (integer) each unit of fertilizer increases the amount of ﬂowers, grouped
in clusters.
● temp (integer) if the temperature recorded is between 20°C and 30°C (bounds
included) the plant grows normally, otherwise all the ﬂowers die, except for a
single survivor at the end of the stem.

*/

function plant(seed, water, fert, temp) {
    let stem = "";
    let flower = "";
    let sum = "";

    for (let i = 0; i < water; i++) {
        stem += "-";
    }
    for (let i = 0; i < fert; i++) {
        flower += seed;
    }

    if (temp >= 20 && temp <= 30) {

        for (let i = 0; i < water; i++) {
            sum += stem + flower;
        }
        return sum
    }
    else {
        for (let i = 0; i < water; i++) {
            sum += stem;
        }
        return sum + seed
    }

}
console.log(plant("@", 3, 3, 25));
console.log(plant("#", 1, 5, 30));
console.log(plant("&", 5, 1, 20));
console.log(plant("§", 3, 3, 15));
